name: Build Better Brightness

on:
  push:

jobs:
  build:
    strategy:
      matrix:
        target: 
          - arm64-v8a
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Android NDK
      uses: nttld/setup-ndk@v1
      id: setup-ndk
      with:
        ndk-version: r26b
        
    - name: Configure CMake
      run: |
        mkdir build
        cd build
        cmake .. -DCMAKE_TOOLCHAIN_FILE=${{ steps.setup-ndk.outputs.ndk-path }}/build/cmake/android.toolchain.cmake -DANDROID_ABI=${{ matrix.target }} -DANDROID_PLATFORM=android-21 -DCMAKE_BUILD_TYPE=Release
        
    - name: Build
      run: |
        cd build
        make
        
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: BetterBrightness-${{ matrix.target }}
        path: build/libBetterBrightness.so
